language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -r requirements_dev.txt
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rhshah
  password:
    secure: RBrDRYEEsuQTXa6JPZvI0/lsQ02ddOvo6zW3fAke7Ju693tqagOqtmH0Sk+livZveOVjRH9gyV5cBoCXnH5xnhD1uXflvn/jYBizbMxASL6raHqeu7N96VDe914IY9NWMOePMgsq8lsOImeH9fGDRc0WqLsS4Np7HmpNW7ESDcRE3sre0Pg+NwPPG9mOP76BpgXmhRwz3DaZW8k4kc6xprmc7csP7ve2Y5MvpbbXIc6GrfJNiWQLDFtewoNDZUZSamUErBeCrG9zxIkjGBjaF+3FANDAGRLiVQyHs9SSp29gtkoXs1UIyY7PDCGrdB9eKzE0Lwx+UYliS3YzYfOYhxk1hUjrL+xzQ8XBadgSuiOpZLy7g7htlLYCkxkSzBBvyrXKzXnh3KcaEqFfmJ0E0h8ULKejUuNJa7ZzsAdua7lEl17Rw1zqA8896zUMckH6o34p71BZyH5sNvOmZXxxSr1ZjU7IwL1EZ+2spum/Naigs1ZelZ2p7QYz+7tD214X5MUYdXSjURhfdzVZ+UDYopTxhsbd8pwkwwqFO7/vZ8lG+0uaPoxNhJ45aItP1yZZa28Wvq57eTVgYbVjipENUN1NrWDxtVW7klxSOsd78FXjkKD3wRHooLc6z6fChWsXYd1GG2U2Dkg/GLbACtIsP3mYudN21ZH9FFp3Y66/EHE=
  on:
    tags: true
    repo: rhshah/process_fastq
    python: 3.6
